# -*- coding: utf-8 -*-
"""Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mhdRVby_FQMNV7HAKdAkTG1eSlQ0N3cS
"""

import pandas as pd

df1 = pd.read_excel("/content/Aracaju.xlsx")
df2 = pd.read_excel("/content/Fortaleza.xlsx")
df3 = pd.read_excel("/content/Natal.xlsx")
df4 = pd.read_excel("/content/Recife.xlsx")
df5 = pd.read_excel("/content/Salvador.xlsx")

df= pd.concat([df1, df2, df3, df4, df5])

df.head()

df.tail()

df.sample(5)

df.dtypes

df["LojaID"] = df["LojaID"].astype("object")

df.dtypes

df.head()

df.isnull().sum()

df["Receita"] = df["Vendas"].mul(df["Qtde"])

df.head()

df["Receita/Vendas"] = df["Receita"] / df["Vendas"]

df.head()

df["Receita"].max()

df["Receita"].min()

df.nlargest(3,"Receita")

df.nsmallest(3,"Receita")

df.groupby("Cidade")["Receita"].sum()

df.sort_values("Receita", ascending= False).head(10)

